from django import forms
from app.models import *

class TicketForm (forms.ModelForm):
    class Meta:
        model = Ticket
        exclude = ('severity', 'status', 'author', 'assignee', 'date_posted')


class TicketAdminForm (forms.ModelForm):
    class Meta:
        model = Ticket
        exclude = ('author', 'date_posted')


class TicketCommentForm (forms.ModelForm):
    class Meta:
        model = TicketComment
        exclude = ('author', 'date_posted', 'ticket', 'autogenerated')


class TicketMilestoneForm (forms.ModelForm):
    class Meta:
        model = TicketMilestone



