#!/bin/bash

# Replace these three settings.
PROJDIR="/home/sma1/sma"
PIDFILE="$PROJDIR/log/fcgi.pid"

echo $PROJDIR
echo $PIDFILE

cd $PROJDIR
if [ -f $PIDFILE ]; then
    kill `cat -- $PIDFILE`
    rm -f -- $PIDFILE
fi
exec /usr/bin/env - \
    PYTHONPATH="../python:.." \
    ./manage.py runfcgi host=127.0.0.1 port=8080 pidfile=$PIDFILE
